# Generated by Django 3.2.6 on 2021-08-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_alter_good_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='is_top',
            new_name='in_stock',
        ),
    ]
