# Generated by Django 3.2.6 on 2021-08-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_rename_is_top_good_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='in_stock',
            new_name='is_discount',
        ),
    ]
