# Generated by Django 4.0.5 on 2022-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_alter_backcall_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
