# Generated by Django 4.0.5 on 2022-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0009_alter_good_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(help_text='This is the description text', max_length=100, null=True),
        ),
    ]
