# Generated by Django 4.0.5 on 2022-06-15 17:23

from django.db import migrations, models
import django.db.models.deletion
import my_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_alter_good_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=my_site.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_site.good')),
            ],
        ),
    ]
